apiVersion: v1
kind: Service
metadata:
  name: ecollect-cdi-svc
  namespace:
spec:
  selector:
    app: ecollect-cdi
  ports:
    - protocol: TCP
      port: 6002
      targetPort: 6002
      nodePort: 30010
  type: NodePort
